### PR TITLE
Fixes #1508: Validation fails to trigger when next field is already filled out

### LINKED ISSUE #1508: Validation fails to trigger when next field is already filled out
To reproduce:

On the index demo, edit the markup to fill in the second field with a valid email address. Load that demo, type "abc" into the first field, tab to the next field, tab back, delete the value.

Expected: "This field is required" error.
Actual: No error

Originally reported as #244, but its really not specific to select elements. Reverted the fix from #396 in 5934f4d4509b900594b40eb4399446dd46debf36, as the caused a regression (#521).

This seems pretty tough to fix, as it scratches on the very basics of how the plugin figures out if a field should be validated or not. Haven't yet been able to come up with a better solution.

### PR DESCRIPTION
**Pull request by Arkni**
See #1508 for more information.

This pull request removes also the need for `lastElement`

### CODE REVIEW

**Comment by Arkni** [comment]
@jzaefferer 

Can you please take a look at this (If you have the time of course).

**Comment by Arkni** [comment]
@staabm 

Could you please review this PR ?

**Comment by staabm** [comment]
@Arkni did you make sure that the unit test fails without your patch?

**Comment by Arkni** [comment]
@staabm 
Yes, I did.

Here it is:
```js
test( "#1508: Validation fails to trigger when next field is already filled out", function() {
	// The next field is already filled out.
	$( "#lastname" ).val( "something" );

	var event     = $.Event( "keyup", { keyCode: 9 } ),
		element   = $( "#firstname" ),
		validator = $( "#testForm1" ).validate();

	// Fill the first element
	element.val( "abc" );

	// Tab to the next field
	element.blur();
	$("#lastname").trigger( event );
	$("#lastname").focus();

	// Tab back to element
	$("#lastname").blur();
	element.trigger( event );
	element.focus();

	// Delete the content
	element.val( "" );
	element.trigger( "keyup" );

	// element should be invalid
	equal( 1, validator.numberOfInvalids(), "The element is not valid" );
});
```

And it fails as expected without my patch.

```
Running "qunit:files" (qunit) task
Testing test/index.html ............................................................................F....................................................................................................................................
>> events - #1508: Validation fails to trigger when next field is already filled out
>> Message: The element is not valid
>> Actual: 1
>> Expected: 0
>> at file:///home/arkni/Git%20Repositories/jquery-validation/test/qunit/qunit.js:1311
>>   at file:///home/arkni/Git%20Repositories/jquery-validation/test/qunit/qunit.js:1907
>>   at file:///home/arkni/Git%20Repositories/jquery-validation/test/test.js:1363
>>   at file:///home/arkni/Git%20Repositories/jquery-validation/test/qunit/qunit.js:895
>>   at file:///home/arkni/Git%20Repositories/jquery-validation/test/qunit/qunit.js:1024
>>   at process (file:///home/arkni/Git%20Repositories/jquery-validation/test/qunit/qunit.js:583)
>>   at begin (file:///home/arkni/Git%20Repositories/jquery-validation/test/qunit/qunit.js:628)
>>   at file:///home/arkni/Git%20Repositories/jquery-validation/test/qunit/qunit.js:644

Warning: 1/1220 assertions failed (5338ms) Use --force to continue.
```

Is this the right way to test it ?

File: src/core.js [hunk 1]
```diff
@@ -420,7 +418,7 @@ $.extend( $.validator, {
 
 				result = this.check( checkElement ) !== false;
 				if ( result ) {
-					delete this.invalid[ checkElement.name ];
+					this.invalid[ checkElement.name ] = false;
```
Comment (Arkni) [inline src/core.js]: Instead of deleting this property, I assign to it `false` to refer to valid element. So:
`false` => valid element
`true` => invalid element

File: src/core.js [hunk 2]
```diff
@@ -510,6 +509,15 @@ $.extend( $.validator, {
 			return this.size() === 0;
 		},
 
+		// Check if the given element is valid
+		// return
+		//          true  If the field is valid
+		//         false  If the field is invalid
+		//     undefined  If the field is not validated yet.
+		isValidElement: function( element ) {
```
Comment (Arkni) [inline src/core.js]: I added also this function in order to check if the given element is valid or not. I don't know if it can be in use to others, but I used it in this patch.

File: src/core.js (hunk 1 above)
Comment (Arkni) [inline src/core.js]: @jzaefferer 
What do you think ?

File: test/test.js [hunk 3]
```diff
@@ -1334,6 +1334,35 @@ test( "don't revalidate the field when pressing special characters", function()
...
+	$("#lastname").blur();
+	element.trigger( event );
+	element.focus();
+
+	// Delete the content
+	element.val( "" );
+	element.trigger( "keyup" );
+
+	// element should be invalid
+	equal( false, validator.isValidElement( element[0] ), "The element is not valid" );
```
Comment (Arkni) [inline test/test.js]: **<< TO ME >>**
This should be changed to
```js
equal( validator.isValidElement( element[0] ), false, "The element is not valid" );
```

**Comment by staabm** [comment]
I will double test your change on monday, thanks

**Comment by Arkni** [comment]
@staabm 
Any chance to test this ?

**Comment by staabm** [comment]
@Arkni just tested your changes locally.

I am running into the following error, in Chrome-Beta and FF-Dev-Edition:
{code}
configuration with attributes : #1508: Validation fails to trigger when next field is already filled out (1, 0, 1)Rerun13 ms
Died on test #1     at file:///C:/Users/mstaab/Documents/GitHub/jquery-validation/test/test.js:1856:1: validator.isValidElement is not a function@ 13 ms
Source: 	
TypeError: validator.isValidElement is not a function
    at Object.<anonymous> (file:///C:/Users/mstaab/Documents/GitHub/jquery-validation/test/test.js:1882:19)
{code}

**Comment by staabm** [comment]
@Arkni just tested your changes.
- manually tested that issue #1508 fails without your test and works with your patch as expected
- unit test looks fine

thanks.

File: src/core.js (hunk 2 above)
Comment (staabm) [inline src/core.js]: having another look at this method...

it assumes that `validate()` was called before, right? I think we should at least mention this precondition in the method doc.

Comment (Arkni) [inline src/core.js]: Yes, you're right.

`validate()` should be called before.
